_wandb:
    value:
        cli_version: 0.19.7
        code_path: code/main.py
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
batch_size:
    value: 256
expected_threshold:
    value: 0.91
k_values:
    value:
        - 1
        - 5
        - 20
        - 50
        - 100
        - 200
model_size:
    value: small
model_type:
    value: dinov2
model_variant:
    value: null
