_wandb:
    value:
        cli_version: 0.19.7
        code_path: code/main.py
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 105
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 3
                - 8
            "12": 0.19.7
            "13": windows-amd64
backbone_type:
    value: dinov2
batch_size:
    value: 20
da_strength:
    value: 1
dataset_name:
    value: cifar10
embedding_dim:
    value: 384
input_size:
    value: 32
is_diet_active:
    value: true
is_rgb:
    value: true
label_smoothing:
    value: 0.3
limit_data:
    value: 1000
lr:
    value: 0.0005
model_size:
    value: small
num_classes:
    value: 10
num_diet_classes:
    value: 10
num_epoch:
    value: 30
projection_dim:
    value: 256
weight_decay:
    value: 0.05
